all: daysCalculatorA daysCalculatorB daysCalculatorC daysCalculatorD daysCalculatorE

daysCalculatorA: daysCalculatorA.c
	gcc -ansi daysCalculatorA.c -o daysCalculatorA
daysCalculatorB: daysCalculatorB.c
	gcc -ansi daysCalculatorB.c -o daysCalculatorB
daysCalculatorC: daysCalculatorC.c
	gcc -ansi daysCalculatorC.c -o daysCalculatorC
daysCalculatorE: daysCalculatorE.c
	gcc -ansi daysCalculatorE.c -o daysCalculatorE
daysCalculatorD: daysCalculatorD.c
	gcc -ansi daysCalculatorD.c -o daysCalculatorD

clean:
	rm *o daysCalculatorA daysCalculatorB daysCalculatorC daysCalculatorD daysCalculatorE 
